Repository Netcracker/qubership-workflow-hub, pull requests merged in 2025-01, with the labels that each got.

#4 Added workflow example publish-on-release-tag.yaml
  docs/examples/publish-on-release-tag.yaml
Labels: enhancement

#10 feat(ci): Add Python release workflow
  .github/workflows/python-publish.yml
  .github/workflows/release-drafter.yml
  docs/examples/python-release.yaml
  docs/examples/upload-to-maven-central.yaml
Labels: feature, ci

#11 feat(ci): Update Maven publish workflow inputs and remove deprecated …
  .github/workflows/maven-publish.yml
  .github/workflows/release-drafter.yml
  .github/workflows/update-pom-release.yml
  README.md
  docs/examples/github-release.yaml
  docs/examples/maven-release.yaml
  docs/examples/python-release.yaml
  docs/examples/release-drafter-config.yml
  docs/examples/upload-to-maven-central.yaml
  docs/reusable/maven-publish_doc.md
  docs/reusable/update-pom-release_doc.md
Labels: feature, ci

#17 Add GitHub Actions for automated publishing and improved documentation
  .github/workflows/create-github-release.yml
  actions/commit-and-push/README.md
  actions/commit-and-push/action.yml
  actions/poetry-publisher/README.md
  actions/poetry-publisher/action.yml
Labels: bug, feature
