Repository Netcracker/qubership-workflow-hub, pull requests merged in 2025-05, with the labels that each got.

#167 fix: Natural language typo fix for README.md
  README.md
Labels: bug

#169 fix: Update testing framework and enhance documentation
  actions/container-package-cleanup/README.md
  actions/container-package-cleanup/dist/index.js
  actions/container-package-cleanup/package-lock.json
  actions/container-package-cleanup/package.json
  actions/container-package-cleanup/src/index.js
  actions/container-package-cleanup/src/report.js
  actions/container-package-cleanup/tests/report.test.js
  actions/container-package-cleanup/tests/wrapper.test.js
Labels: bug, enhancement

#165 fix: maven snapshots deploy
  .github/workflows/re-maven-snapshot-deploy.yaml
Labels: bug

#183 feat(ci): added maven-cache and deb package installation speedup
  .github/workflows/re-maven-snapshot-deploy.yaml
Labels: enhancement

#171 feat: added a new maven-snapshot-deploy action
  actions/maven-snapshot-deploy/README.md
  actions/maven-snapshot-deploy/action.yaml
  docs/README.md
Labels: bug, documentation, enhancement

#184 feat: added maven-version input parameter to re-maven-snapshot-deploy…
  .github/workflows/re-maven-snapshot-deploy.yaml
  actions/maven-release/action.yaml
  actions/maven-snapshot-deploy/action.yaml
Labels: enhancement

#186 feat: Enhance metadata action with detailed logging and summary report
  actions/metadata-action/README.md
  actions/metadata-action/config.schema.json
  actions/metadata-action/dist/config.schema.json
  actions/metadata-action/dist/index.js
  actions/metadata-action/src/extractor.js
  actions/metadata-action/src/index.js
  actions/metadata-action/src/loader.js
  actions/metadata-action/src/report.js
Labels: enhancement

#201 bug: Enhance template handling and improve GitHub context flattening
  actions/metadata-action/dist/index.js
  actions/metadata-action/src/index.js
Labels: bug, refactor

#204 fix: Add validation for templates in findTemplate function
  actions/metadata-action/dist/index.js
  actions/metadata-action/src/index.js
Labels: bug
