Repository Netcracker/qubership-workflow-hub, pull requests merged in 2025-03, with the labels that each got.

#60 feat: Add reusable GitHub Actions workflow for Maven Central snapshot deployment
  .github/workflows/maven-central-snapshot-deploy-reusable.yaml
Labels: enhancement

#62 feat: added platforms to docker-publish
  .github/workflows/docker-publish.yml
Labels: enhancement

#54 feat: cdxgen action prepares cyclondx report
  actions/cdxgen/action.yaml
Labels: bug, enhancement

#69 feat: Broadcast reusable workflow added to propagate files across organization
  .github/workflows/broadcast-files.yml
  CODEOWNERS
  docs/README.md
  docs/reusable/broadcast-files.md
Labels: enhancement

#88 feat(ci): Update super-linter configuration and add new linters for improved code quality
  .github/linters/.checkov.yaml
  .github/linters/.eslintrc.yml
  .github/linters/.flake8
  .github/linters/.golangci.yml
  .github/linters/.jscpd.json
  .github/linters/.yaml-lint.yml
  .github/linters/actionlint.yml
  .github/super-linter.env
  .github/workflows/super-linter.yaml
Labels: enhancement

#66 feat: add Verify JSON file action with schema validation
  actions/verify-json/README.md
  actions/verify-json/action.yaml
Labels: enhancement

#95 feat: Migrate metadata action to new structure with configuration schema
  actions/github-metadata/.gitignore
  actions/github-metadata/README.md
  actions/github-metadata/dist/index.js
  actions/github-metadata/src/configLoader.js
  actions/github-metadata/src/index.js
  actions/metadata-action/.gitignore
  actions/metadata-action/README.md
  actions/metadata-action/action.yml
  actions/metadata-action/config.schema.json
  actions/metadata-action/dist/index.js
  actions/metadata-action/package-lock.json
  actions/metadata-action/package.json
  actions/metadata-action/src/extractor.js
  actions/metadata-action/src/index.js
  actions/metadata-action/src/loader.js
Labels: feature

#98 feat: Added parameters for cdxgen workflow and action
  .github/workflows/cdxgen.yaml
  actions/cdxgen/action.yaml
Labels: enhancement

#99 fix(ci): Remove unused input parameters from cdxgen workflow
  .github/workflows/cdxgen.yaml
  actions/cdxgen/action.yaml
Labels: bug

#101 fix: Broadcast workflow updated with correct branching settings
  .github/workflows/broadcast-files.yml
  .github/workflows/cla.yaml
  docs/reusable/broadcast-files.md
Labels: bug

#107 feat: Add Maven deploy reusable workflow for snapshot artifacts
  .github/workflows/re-maven-snapshot-deploy.yaml
Labels: enhancement

#111 fix: update Maven deploy workflow to handle snapshot and non-snapshot…
  .github/workflows/re-maven-snapshot-deploy.yaml
Labels: bug

#117 fix: Enhance metadata action and Docker publish workflow
  .github/workflows/docker-publish.yml
  actions/metadata-action/config.schema.json
  actions/metadata-action/dist/config.schema.json
  actions/metadata-action/dist/index.js
  actions/metadata-action/src/index.js
Labels: bug

#123 docs: Update maven-publish documentation to include distributionManagement and snapshots repository sections
  docs/maven-publish-pom-preparation_doc.md
Labels: documentation

#124 feat: Improve metadata action error handling and dist-tag management
  actions/metadata-action/dist/index.js
  actions/metadata-action/src/index.js
  actions/metadata-action/src/loader.js
Labels: bug
