Repository Netcracker/qubership-workflow-hub, pull requests merged in 2025-09, with the labels that each got.

#320 fix(ci): fix for link-checker workflow
  .github/workflows/link-checker.yaml
Labels: bug

#329 feat: Added a new optional parameter to Container Package Cleanup Action
  .gitignore
  actions/container-package-cleanup/README.md
  actions/container-package-cleanup/action.yml
  actions/container-package-cleanup/dist/index.js
  actions/container-package-cleanup/src/index.js
  actions/container-package-cleanup/src/strategy/maven.js
  actions/maven-release/README.md
  actions/maven-snapshot-deploy/README.md
Labels: bug, documentation, enhancement

#368 fix: update action.yaml
  actions/charts-values-update-action/action.yaml
Labels: bug

#377 docs: update release drafter workflow path in README
  README.md
Labels: documentation

#395 feat: charts-values-update-action can optionally publish charts to ghcr.io
  actions/charts-values-update-action/README.md
  actions/charts-values-update-action/action.yaml
  actions/charts-values-update-action/image-versions-replace.py
Labels: bug, documentation, enhancement
