Repository Netcracker/qubership-workflow-hub, pull requests merged in 2025-10, with the labels that each got.

#397 fix: Fix metadata-action runNumber alias resolution bug
  actions/metadata-action/dist/index.js
  actions/metadata-action/src/index.js
Labels: bug

#405 feat: Add wait-for-workflow GitHub Action and update documentation
  actions/wait-for-workflow/README.md
  actions/wait-for-workflow/action.yml
  docs/actions-workflows-catalog.md
  docs/secrets-and-vars.md
Labels: documentation, enhancement, refactor

#400 fix: Update Trivy severity levels and enhance Grype SARIF filtering logic
  .github/workflows/re-security-scan.yml
Labels: bug

#407 BREAKING: deleted unused/deprecated reusable workflows
  .github/workflows/create-github-release.yml
  .github/workflows/docker-publish.yml
  .github/workflows/maven-central-snapshot-deploy-reusable.yaml
  .github/workflows/maven-publish.yml
  .github/workflows/re-maven-snapshot-deploy.yaml
  .github/workflows/release-drafter.yml
  .github/workflows/scout-repo-scan.yaml
  .github/workflows/spelling.yaml
  .github/workflows/tag-creator.yml
Labels: breaking-change
