Repository Netcracker/qubership-workflow-hub, pull requests merged in 2025-04, with the labels that each got.

#135 feat: single repo update option added
  .github/workflows/broadcast-files.yml
Labels: enhancement

#136 feat: Add 'store-input-params' action
  actions/store-input-params/README.md
  actions/store-input-params/action.yaml
Labels: enhancement

#130 docs: Update Maven publish documentation to include profiles for central and GitHub packages
  docs/maven-publish-pom-preparation_doc.md
Labels: documentation

#139 feat: Broadcast workflow optimization
  .github/workflows/broadcast-files.yml
Labels: enhancement

#141 feat: Add Docker Build and Publish action with enhanced input options and metadata handling
  .github/workflows/docker-publish.yml
  actions/docker-action/README.md
  actions/docker-action/action.yml
Labels: bug, enhancement

#144 feat: Add Tag Composite Action with enhanced input/output management and streamlined tagging process
  actions/tag-action/README.md
  actions/tag-action/action.yml
Labels: enhancement

#147 fix: Issue with 'dist-tag cant find value from code. Rename 'dist-tags' to 'distribution-tag' and clean up metadata action
  actions/metadata-action/config.schema.json
  actions/metadata-action/dist/config.schema.json
  actions/metadata-action/dist/index.js
  actions/metadata-action/src/index.js
Labels: bug

#155 feat: Implement GhCommand class and update action inputs
  actions/pr-assigner/README.md
  actions/pr-assigner/action.yml
  actions/pr-assigner/config.schema.json
  actions/pr-assigner/dist/config.schema.json
  actions/pr-assigner/dist/index.js
  actions/pr-assigner/src/command.js
  actions/pr-assigner/src/index.js
Labels: bug, enhancement

#145 feat(ci): Added helm-charts-release action
  actions/helm-charts-release/README.md
  actions/helm-charts-release/action.yaml
  actions/helm-charts-release/helm-charts-release-config.yaml
Labels: enhancement

#158 docs: Update README.md
  actions/custom-event/README.md
Labels: documentation

#113 feat: cdxgen refactoring
  .github/workflows/cdxgen.yaml
  actions/cdxgen/action.yaml
Labels: bug, enhancement

#131 feat: Added maven-release action
  .github/workflows/tag-creator.yml
  actions/commit-and-push/README.md
  actions/commit-and-push/action.yml
  actions/maven-release/action-script.sh
  actions/maven-release/action.yaml
Labels: bug, enhancement

#162 fix: ensure fetch-depth is set for checkout
  actions/tag-action/action.yml
Labels: bug

#163 feat: Enhance archive and upload action with improved configuration options
  actions/archive-and-upload-assets/README.md
  actions/archive-and-upload-assets/action.yml
  actions/archive-and-upload-assets/config.schema.json
  actions/archive-and-upload-assets/dist/index.js
  actions/archive-and-upload-assets/index.js
  actions/archive-and-upload-assets/loader.js
  actions/archive-and-upload-assets/package-lock.json
  actions/archive-and-upload-assets/package.json
Labels: bug, enhancement
