Repository Netcracker/qubership-workflow-hub, pull requests merged in 2025-06, with the labels that each got.

#206 feat: Update Maven GitHub Action configuration
  actions/maven-snapshot-deploy/action.yaml
Labels: bug, enhancement

#216 feat: Implement asset upload action with archiving and reporting
  actions/assets-action/.gitignore
  actions/assets-action/README.md
  actions/assets-action/action.yml
  actions/assets-action/config.schema.json
  actions/assets-action/dist/index.js
  actions/assets-action/package-lock.json
  actions/assets-action/package.json
  actions/assets-action/src/archiveUtils.js
  actions/assets-action/src/assetsUploader.js
  actions/assets-action/src/index.js
  actions/assets-action/src/loader.js
  actions/assets-action/src/report.js
  actions/assets-action/src/retry.js
Labels: enhancement

#218 feat: add glob dependency and enhance asset processing
  actions/assets-action/dist/index.js
  actions/assets-action/package-lock.json
  actions/assets-action/package.json
  actions/assets-action/src/assetsUploader.js
  actions/assets-action/src/index.js
Labels: enhancement

#220 feat: add compression level input for asset archiving
  actions/assets-action/action.yml
  actions/assets-action/dist/index.js
  actions/assets-action/src/archiveUtils.js
  actions/assets-action/src/index.js
Labels: enhancement

#222 bug: Bug/issues 221 [tag-action] Cant force create tag [rejected]
  actions/tag-action/action.yml
Labels: bug
