Repository Netcracker/qubership-workflow-hub, pull requests merged in 2025-08, with the labels that each got.

#285 feat: added spelling.yaml
  .github/workflows/spelling.yaml
Labels: enhancement

#283 feat: add security scan inputs and update README for Docker action.
  .gitignore
  actions/docker-action/README.md
  actions/docker-action/action.yml
Labels: bug, documentation, enhancement

#291 feat: charts values update action
  actions/charts-values-update-action/action.yaml
  actions/charts-values-update-action/image-versions-replace.py
Labels: enhancement

#298 fix: Build-args input handling in action.yml
  actions/docker-action/action.yml
Labels: bug

#299 docs: Enhance documentation and restructure README files
  README.md
  actions/charts-values-update-action/README.md
  actions/charts-values-update-action/charts-values-update-config.yaml
  actions/metadata-action/README.md
  actions/pr-assigner/README.md
  docs/README.md
  docs/actions-workflows-catalog.md
  docs/code-of-conduct-prs.md
  docs/getting-started.md
  docs/issue-guidelines.md
  docs/secrets-and-vars.md
  docs/standards-and-change-policy.md
Labels: documentation

#312 feat: Enhance Docker action to output metadata file details
  actions/docker-action/action.yml
Labels: enhancement
