Repository Netcracker/qubership-workflow-hub, pull requests merged in 2025-02, with the labels that each got.

#27 Fix release drafter workflow to use correct branch reference and set version environment variable
  .github/workflows/auto-labeler.yaml
  .github/workflows/release-drafter.yml
Labels: bug, ci

#28 feat: #9 Add workflows for collecting commit messages and checking Conventional Commits in PRs
  .github/workflows/pr-collect-commit-messages.yaml
  .github/workflows/pr-conventional-commits.yaml
  .github/workflows/pr-lint-title.yaml
  README.md
  actions/pr-add-messages/README.md
  actions/pr-add-messages/action.yaml
  docs/examples/pr-collect-commit-messages.yaml
  docs/examples/pr-conventional-commits.yaml
  docs/examples/pr-lint-title.yaml
Labels: enhancement, ci

#36 fix: Refactor commit-and-push action to simplify push command
  actions/commit-and-push/action.yml
Labels: refactor

#37 fix: Update action.yaml
  actions/pr-add-messages/action.yaml
Labels: bug

#38 feat: Added new action to generate SBOM files
  actions/cdxgen/action.yaml
Labels: enhancement

#44 feat: readme improvement
  README.md
Labels: refactor

#53 feat: Add GitHub Metadata Action for version string generation
  actions/github-metadata/.gitignore
  actions/github-metadata/README.md
  actions/github-metadata/action.yml
  actions/github-metadata/dist/index.js
  actions/github-metadata/package-lock.json
  actions/github-metadata/package.json
  actions/github-metadata/src/configLoader.js
  actions/github-metadata/src/index.js
  actions/github-metadata/src/refExtractor.js
Labels: enhancement

#52 feat: added license report to cdxgen
  actions/cdxgen/action.yaml
Labels: enhancement
