Repository Netcracker/qubership-workflow-hub, pull requests merged in 2025-07, with the labels that each got.

#258 feat: helm-charts-release action improvement
  actions/helm-charts-release/README.md
  actions/helm-charts-release/action.yaml
  actions/helm-charts-release/helm-charts-release-config.yaml
  actions/helm-charts-release/image-versions-replace.py
Labels: bug, documentation, enhancement

#260 feat: adds an action to clean up the Maven registry on GitHub and a Docker image layer remover for the architecture.
  actions/container-package-cleanup/dist/index.js
  actions/container-package-cleanup/src/index.js
  actions/container-package-cleanup/src/report.js
  actions/container-package-cleanup/src/reports/containerReport.js
  actions/container-package-cleanup/src/reports/mavenReport.js
  actions/container-package-cleanup/src/strategy/abstractPackageStrategy.js
  actions/container-package-cleanup/src/strategy/container.js
  actions/container-package-cleanup/src/strategy/maven.js
  actions/container-package-cleanup/src/strategy/strategyRegistry.js
  actions/container-package-cleanup/src/utils/apiCaller.js
  actions/container-package-cleanup/src/utils/loader.js
  actions/container-package-cleanup/src/utils/wildcardMatcher.js
  actions/container-package-cleanup/src/utils/wrapper.js
Labels: enhancement

#261 docs: Remove legacy files and enhance package cleanup action
  actions/container-package-cleanup/README.md
Labels: documentation, enhancement

#263 feat: Added Auto-assign Project to issue
  .github/workflows/auto-assign-project-to-issue.yml
Labels: enhancement

#267 feat: Updated the npm_publish
  .github/workflows/re-npm-publish.yml
  README.md
Labels: enhancement

#272 feat: added special case 'semver' to filter containers by tag
  actions/container-package-cleanup/README.md
  actions/container-package-cleanup/dist/index.js
  actions/container-package-cleanup/src/utils/wildcardMatcher.js
Labels: bug
